### PR TITLE
rewrote TimedLoop, add returns to add|removeCondition in Trigger, Assert (wasn't able to use Wurstunit that's why i wrote it), fixed/tested OnUnitEnterLeave and UnitIndexer

### PR DESCRIPTION
**Pull request by Ruk33**

### CODE REVIEW

**Comment by Ruk33** [comment]
fixed initialization on OnUnitEnterLeave package, also DamageDetection rewrited mainly because to avoid the use of one giant trigger

**Comment by Cokemonkey11** [comment]
You have merge conflicts, you should also squash your commits and use a separate branch

**Comment by Ruk33** [comment]
uhmm, i think the std library should be separated from the compiler...

**Comment by Frotty** [comment]
it will be, when we have some sort of dependency management.

**Comment by peq** [comment]
> Also please create smaller pull requests, which can be reviewed easier.

This would be good. Create one branch per feature/ pull request to do this.

**Pull request closed without merging**
