### PR TITLE
add some documentation about jurst and managing legacy maps

### PR DESCRIPTION
**Pull request by Cokemonkey11**
Related #349 

I think there's some language which is not quite right ("translate vjass"?) Let me know what you think.

### CODE REVIEW

**Comment by peq** [comment]
Please try to keep one sentence per line. It is easier to read diffs that way.

> the Wurstpack World Editor will parse jass/vjass, in addition to compiling your Wurst code.

It will only parse jass unless you enable the vjass compiler.

> translating existing vJass to Jurst automatically

There is no automatic translation. The command just extracts the trigger code as it is and puts it into files.

**Comment by Cokemonkey11** [comment]
I'll not have time anymore to make the required changes. @Frotty can you take this over please?

**Comment by Cokemonkey11** [comment]
@peq I've fixed this up.

**Comment by Frotty** [comment]
ty

**Pull request merged**
