### PR TITLE
[stl] add texttag critical strike macro

### PR DESCRIPTION
**Pull request by Cokemonkey11**
Credits: http://www.wc3c.net/showthread.php?t=101963

### CODE REVIEW

**Comment by peq** [comment]
I think it is strange that this should be an extension function on `texttag`. It is a very specific use case and should probably be in a separate package like `StandardTexttags`.

**Comment by Frotty** [comment]
Indeed. Together with others like bounty, exp, miss, etc.

**Comment by Cokemonkey11** [comment]
I can make it right now since you both seem to be in agreement?

For the API, how do you feel about

```
texttagCriticalStrike
texttagShadowStrike
texttagMiss
```

etc

**Comment by peq** [comment]
I like it when function names have a verb, like `createCriticalStrikeText(...)`.

**Comment by Cokemonkey11** [comment]
standby for new pr

**Pull request closed without merging**
