### PR TITLE
Updated jmpq3

### PR DESCRIPTION
**Pull request by Crigges**
The old old jar was causing some bugs, which should be fixed now. See #421

### CODE REVIEW

**Comment by Frotty** [comment]
"should be" or did you actually test it for once?

**Comment by Crigges** [comment]
I was able to reproduce the bug inside the jmpq libary. After the fix the same piece of code was working. I aswell tested the new .jar inside the we without any problems.

**Comment by Frotty** [comment]
This breaks maps for ghost bots again, pls fix.

**Comment by Crigges** [comment]
Ghost can host maps compiled with the new jar now.

**Comment by Frotty** [comment]
I will confirm this and then merge.

**Pull request merged**
