### PR TITLE
Rewrote from scratch.

### PR DESCRIPTION
**Pull request by muzzel**

### CODE REVIEW

**Comment by peq** [comment]
This does not look like it is backwards compatible with the old library, so maybe it is better to publish this as a separate library? Or a different package?

I have to work on integrating some dependency management into Wurst.

**Comment by Frotty** [comment]
Who used the old crappy library? :palm_tree:

**Comment by Crigges** [comment]
I don't

**Comment by peq** [comment]
It is not just about this package: In general we have to make the standard library smaller and move more things (or everything) to external, versioned dependencies. I don't like the current situation where adding a function to the standard library can break someones code just by upgrading Wurst. 

But yeah, as long as I did not implement the tools to make this work we can also merge this into the standard library.

**Comment by Frotty** [comment]
So this won't be a problem for the next 1-2 years :shell:

**Comment by peq** [comment]
let's see :dolphin:

**Comment by muzzel** [comment]
I thought about providing an additional constructor with the same signature as the old one, but in the oly library there are unused constructor arguments and I definitely wont add sh*t like that only for compatibility.

**Pull request merged**
